Repository asdvsvs/my-paldo-trip-fe, pull requests merged in 2024-01, with the labels that each got.

#17 Feat/user
  src/assemble/HomePage.vue
  src/components/layout/VueHeader.vue
  src/router.js
  src/views/sample/VueAbout.vue
  src/views/sample/VueDataTest.vue
  src/views/sample/VueHome.vue
  src/views/sample/VueInputDataTest.vue
  src/views/user/applicationGetForm.vue
  src/views/user/applicationListForm.vue
  src/views/user/applicationSubmitForm.vue
  src/views/user/deleteUser.vue
  src/views/user/getUser.vue
  src/views/user/getUserList.vue
  src/views/user/loginUser.vue
  src/views/user/signupPage.vue
  src/views/user/updateUser.vue
Labels: feat

#37 요청 주소 vue.config.js에서 관리
  src/views/sample/VueDataTest.vue
  src/views/sample/VueInputDataTest.vue
  src/views/user/applicationGetForm.vue
  src/views/user/applicationListForm.vue
  src/views/user/applicationSubmitForm.vue
  src/views/user/deleteUser.vue
  src/views/user/getUser.vue
  src/views/user/getUserList.vue
  src/views/user/loginUser.vue
  src/views/user/signupPage.vue
  src/views/user/updateUser.vue
  vue.config.js
Labels: feat

#32 코스, 댓글, 좋아요 api 호출 성공
  src/router.js
  src/views/comment/addComment.vue
  src/views/course/addCourse.vue
  src/views/course/deleteCourse.vue
  src/views/course/deleteCourseFile.vue
  src/views/course/getCourse.vue
  src/views/course/getCourseList.vue
  src/views/course/updateCourse.vue
  src/views/course/uploadCourseFile.vue
  src/views/like/toggleLike.vue
Labels: feat

#42 여행정보, 후기, 여행파일 전체조회
  src/router.js
  src/views/trip/CreateTrip.vue
  src/views/trip/GetTrip.vue
  src/views/trip/GetTripList.vue
  src/views/trip/UpdateTrip.vue
  src/views/trip/getTripFileList.vue
Labels: feat

#44 feat : 자동 배포 workflow
  .github/workflows/main.yml
Labels: feat

#58 여행정보 파일관련 페이지, url수정
  src/router.js
  src/views/trip/CreateTrip.vue
  src/views/trip/GetTrip.vue
  src/views/trip/GetTripList.vue
  src/views/trip/UpdateTrip.vue
  src/views/trip/getTripFile.vue
  src/views/trip/getTripFileList.vue
Labels: feat

#71 배포 환경에서 카카오 로그인 버그 수정
  src/components/layout/VueHeader.vue
  src/router.js
  src/views/user/RedirectPage.vue
  src/views/user/getUserList.vue
  src/views/user/loginUser.vue
Labels: bug

#73 Course, Comment 수정
  src/views/comment/addComment.vue
  src/views/course/deleteCourse.vue
  src/views/course/deleteCourseFile.vue
  src/views/course/getCourse.vue
  src/views/course/getCourseList.vue
  src/views/course/updateCourse.vue
  src/views/like/toggleLike.vue
Labels: feat, refactor

#74 fix: 채팅페이지 이동할 때 토큰 파라미터로 넘기도록 변경 및 기타 프론트 변경
  src/assemble/HomePage.vue
  src/components/layout/VueHeader.vue
  src/router.js
  src/views/user/deleteUser.vue
  src/views/user/getMyProfile.vue
  src/views/user/updateUser.vue
Labels: feat

#75 fix : 채팅 ip 변경
  src/components/layout/VueHeader.vue
Labels: bug

#77 Course 목록조회 카드형변경, 관련여행정보 표시 등등
  src/assemble/CourseUpdatePage.vue
  src/router.js
  src/views/comment/addComment.vue
  src/views/course/addCourse.vue
  src/views/course/deleteCourse.vue
  src/views/course/deleteCourseFile.vue
  src/views/course/getCourse.vue
  src/views/course/getCourseList.vue
  src/views/course/manageCourseFile.vue
  src/views/course/updateCourse.vue
  src/views/course/uploadCourseFile.vue
  src/views/like/toggleLike.vue
Labels: fix, feat, refactor

#78 Course 단건 조회시 관련여행정보 카드형식으로 표시, 삭제버튼 Course단건조회페이지에 병합, 코스의 작성자와로그인한 유저가 같을 때 수정,삭제버튼 표시
  src/assemble/SingleCoursePage.vue
  src/views/comment/addComment.vue
  src/views/course/addCourse.vue
  src/views/course/deleteCourse.vue
  src/views/course/getCourse.vue
  src/views/course/getCourseList.vue
  src/views/course/manageCourseFile.vue
  src/views/course/updateCourse.vue
  src/views/like/toggleLike.vue
Labels: fix, feat, refactor

#76 [#7] fix : 여행정보 목록 카드형식으로 조회되도록 변경, 스타일 수정
  src/views/trip/GetTripList.vue
Labels: refactor

#80 feat : 메인 페이지
  src/assemble/HomePage.vue
  src/views/home/popularCourse.vue
  src/views/home/popularTrip.vue
  src/views/sample/VueHome.vue
Labels: feat

#81 fix : 메인페이지 정렬
  src/views/home/popularTrip.vue
Labels: fix

#84 fix : 여행정보 생성 및 삭제 시 도시이름을 입력하도록 수정
  src/views/trip/CreateTrip.vue
  src/views/trip/UpdateTrip.vue
Labels: fix
