Repository asdvsvs/my-paldo-trip-fe, pull requests merged in 2024-02, with the labels that each got.

#87 nginx 다른 인스턴스로 분리로 인한 gitflows 수정
  .github/workflows/main.yml
  src/views/user/updateUser.vue
  vue.config.js
Labels: fix

#88 fix : 채팅 url 수정
  src/components/layout/VueHeader.vue
Labels: bug

#89 fix : 빌드 후 dist 폴더만 넘기도록 변경
  .github/workflows/main.yml
Labels: fix

#90 fix : 빌드 후 dist 폴더만 넘기도록 변경
  .github/workflows/main.yml
Labels: fix

#86 [#85] feat : 날씨 조회
  src/router.js
  src/views/city/getProvinceList.vue
  src/views/weather/getWeather.vue
Labels: feat

#91 백엔드 변경으로 프론트엔드 수정, 편의성 개선
  src/views/course/addCourse.vue
  src/views/course/getCourseList.vue
  src/views/home/popularCourse.vue
  src/views/home/popularTrip.vue
  src/views/trip/GetTripList.vue
Labels: feat
